spring:

  application:
    name: configserver
  cloud:
    config:
      server:
         git:
           uri: https://github.com/DouglasProenca/Microservicos-CR7Imports-Repository
           default-label: main 

server:
  port: 8889  